### ISSUE TITLE
Feedback on the landing page

### ISSUE THREAD

**Issue by ampaire** [BuildForSDGCohort2/Team-225-Frontend#25]
Cool stuff there guys 💪, however, the landing page seems to have a few issues especially on a mobile platform.
1. The logo gets displaced when you scroll down to a height of about >=300px
2. The button is a little too big
3. Is it possible to make the images a little smaller?

**Comment by SaidiAli** [comment]
Yeah, the alignment is a little off.
If you’re fully back you back probably help out on it. 
You can quickly create an issue for it. 💪

**Comment by SaidiAli** [comment]
Will create a good issue for it.
